services:
  - type: web
    name: portafolio-gaso
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        headers:
          - name: X-Frame-Options
            value: DENY
          - name: X-Content-Type-Options
            value: nosniff
      - path: "*.js"
        headers:
          - name: Content-Type
            value: application/javascript
      - path: "*.mjs"
        headers:
          - name: Content-Type
            value: application/javascript